#!/bin/sh
# generate-frigate-config.sh
# Auto-generates Frigate config.yml from CAMERA_*_RTSP_URL environment variables.
# Usage: This runs as the Frigate container entrypoint before Frigate starts.
#
# Convention: For each camera, set env vars in .env:
#   CAMERA_<NAME>_RTSP_URL          — the RTSP stream URL (required)
#   CAMERA_<NAME>_SUBSTREAM_URL     — optional lower-res substream for detection
#   CAMERA_<NAME>_DETECT_WIDTH      — optional per-camera detect width
#   CAMERA_<NAME>_DETECT_HEIGHT     — optional per-camera detect height
#   CAMERA_<NAME>_DETECT_FPS        — optional per-camera detect FPS
#   CAMERA_<NAME>_ZONES             — optional zone definitions
#
# Example:
#   CAMERA_FRONT_RTSP_URL=rtsp://user:pass@192.168.1.50/stream1
#   CAMERA_FRONT_SUBSTREAM_URL=rtsp://user:pass@192.168.1.50/stream2
#   CAMERA_FRONT_DETECT_WIDTH=1920
#   CAMERA_FRONT_DETECT_HEIGHT=1080
#   CAMERA_BACK_RTSP_URL=rtsp://user:pass@192.168.1.51/stream1
#   CAMERA_FRONT_ZONES=front_door:0.05,0.95,0.38,0.95,0.38,0.40,0.05,0.40

set -e

CONFIG_DIR="${FRIGATE_CONFIG_DIR:-/config}"
CONFIG_FILE="${CONFIG_DIR}/config.yml"
DETECT_WIDTH="${FRIGATE_DETECT_WIDTH:-1280}"
DETECT_HEIGHT="${FRIGATE_DETECT_HEIGHT:-720}"
DETECT_FPS="${FRIGATE_DETECT_FPS:-15}"

# Discover cameras from environment variables matching CAMERA_*_RTSP_URL
# Only include cameras whose URL is non-empty.
CAMERAS=""
for var in $(env | grep '^CAMERA_.*_RTSP_URL=' | grep -v '_SUBSTREAM_' | sed 's/=.*//' | sort); do
    eval url_val="\${$var}"
    if [ -z "$url_val" ]; then
        continue
    fi
    # Extract camera name: CAMERA_FRONT_RTSP_URL -> front
    name=$(echo "$var" | sed 's/^CAMERA_//;s/_RTSP_URL$//' | tr '[:upper:]' '[:lower:]')
    if [ -n "$name" ]; then
        CAMERAS="${CAMERAS} ${name}"
    fi
done

# Trim leading space
CAMERAS=$(echo "$CAMERAS" | sed 's/^ //')

if [ -z "$CAMERAS" ]; then
    echo "generate-frigate-config: WARNING — No cameras configured (all RTSP URLs empty)."
    echo "generate-frigate-config: Frigate will start with no cameras."
    # Write a minimal valid config so Frigate always starts.
    cat > "$CONFIG_FILE" <<ENDMINIMAL
# Auto-generated by generate-frigate-config.sh
# No cameras configured — add CAMERA_*_RTSP_URL env vars and restart.

mqtt:
  enabled: false

tls:
  enabled: false

auth:
  enabled: false

birdseye:
  enabled: true

record:
  enabled: false

detectors:
  cpu1:
    type: cpu

cameras: {}
ENDMINIMAL
    echo "generate-frigate-config: Written minimal config (0 cameras) to ${CONFIG_FILE}"
    exec "$@"
fi

echo "generate-frigate-config: Discovered cameras: ${CAMERAS}"

# Build go2rtc streams section
GO2RTC_STREAMS=""
for cam in $CAMERAS; do
    upper=$(echo "$cam" | tr '[:lower:]' '[:upper:]')
    rtsp_var="CAMERA_${upper}_RTSP_URL"
    sub_var="CAMERA_${upper}_SUBSTREAM_URL"
    eval rtsp_url="\${$rtsp_var}"
    eval sub_url="\${$sub_var:-}"
    GO2RTC_STREAMS="${GO2RTC_STREAMS}
    cam_${cam}:
      - \"${rtsp_url}\"
    cam_${cam}_live:
      - \"ffmpeg:cam_${cam}#video=h264\""

    # Add substream if defined (for dual-stream: detect on sub, snapshots on main)
    if [ -n "$sub_url" ]; then
        GO2RTC_STREAMS="${GO2RTC_STREAMS}
    cam_${cam}_sub:
      - \"${sub_url}\""
    fi
done

# Build cameras section
CAMERAS_SECTION=""
for cam in $CAMERAS; do
    upper=$(echo "$cam" | tr '[:lower:]' '[:upper:]')
    zones_var="CAMERA_${upper}_ZONES"
    eval zones_val="\${$zones_var:-}"

    # Per-camera detection resolution (falls back to global)
    cam_dw_var="CAMERA_${upper}_DETECT_WIDTH"
    cam_dh_var="CAMERA_${upper}_DETECT_HEIGHT"
    cam_fps_var="CAMERA_${upper}_DETECT_FPS"
    eval cam_dw="\${$cam_dw_var:-$DETECT_WIDTH}"
    eval cam_dh="\${$cam_dh_var:-$DETECT_HEIGHT}"
    eval cam_fps="\${$cam_fps_var:-$DETECT_FPS}"

    # Check if substream is available for dual-stream setup
    sub_var="CAMERA_${upper}_SUBSTREAM_URL"
    eval sub_url="\${$sub_var:-}"

    # Build zones YAML if defined
    ZONES_YAML=""
    if [ -n "$zones_val" ]; then
        ZONES_YAML="
    zones:"
        # Parse semicolon-separated zone definitions: name:coords;name2:coords2
        IFS=';'
        for zone_def in $zones_val; do
            zone_name=$(echo "$zone_def" | cut -d: -f1)
            zone_coords=$(echo "$zone_def" | cut -d: -f2-)
            ZONES_YAML="${ZONES_YAML}
      ${zone_name}:
        coordinates: ${zone_coords}
        inertia: 3
        loitering_time: 0"
        done
        unset IFS
    fi

    # Calculate snapshot height based on detect resolution for quality
    snap_height=720
    if [ "$cam_dh" -ge 1080 ] 2>/dev/null; then
        snap_height=1080
    fi

    # Build ffmpeg inputs (dual-stream or single-stream)
    if [ -n "$sub_url" ]; then
        # Dual-stream: main stream for snapshots (full resolution), sub for detect (lighter)
        FFMPEG_INPUTS="      inputs:
        - path: rtsp://127.0.0.1:8554/cam_${cam}
          input_args: preset-rtsp-restream
          roles:
            - record
            - snapshots
        - path: rtsp://127.0.0.1:8554/cam_${cam}_sub
          input_args: preset-rtsp-restream
          roles:
            - detect"
    else
        # Single stream: same stream for detect and snapshots
        FFMPEG_INPUTS="      inputs:
        - path: rtsp://127.0.0.1:8554/cam_${cam}
          input_args: preset-rtsp-restream
          roles:
            - detect
            - snapshots"
    fi

    CAMERAS_SECTION="${CAMERAS_SECTION}
  cam_${cam}:
    enabled: true
    live:
      streams:
        main: cam_${cam}_live
    detect:
      enabled: true
      width: ${cam_dw}
      height: ${cam_dh}
      fps: ${cam_fps}
    ffmpeg:
${FFMPEG_INPUTS}
    motion:
      mask:
        - 0,0,1,0,1,0.06,0,0.06${ZONES_YAML}
    snapshots:
      enabled: true
      quality: 95
      height: ${snap_height}
"
done

# Build tracked objects from TRACKED_ITEMS env var (fallback to defaults)
TRACKED_ITEMS="${TRACKED_ITEMS:-person,car,motorcycle,bus,backpack,suitcase,handbag}"
TRACK_LIST=""
IFS=','
for item in $TRACKED_ITEMS; do
    item=$(echo "$item" | sed 's/^ *//;s/ *$//')
    TRACK_LIST="${TRACK_LIST}
    - ${item}"
done
unset IFS

# Write the config file
cat > "$CONFIG_FILE" <<ENDCONFIG
# Auto-generated by generate-frigate-config.sh
# Do not edit manually — changes will be overwritten on container restart.
# Configure cameras via CAMERA_*_RTSP_URL environment variables in .env.

mqtt:
  enabled: false

tls:
  enabled: false

auth:
  enabled: false

birdseye:
  enabled: true

record:
  enabled: false

snapshots:
  enabled: true
  retain:
    default: 7

objects:
  track:${TRACK_LIST}
  filters:
    person:
      min_score: 0.20
      threshold: 0.60
      min_area: 1000

detectors:
  cpu1:
    type: cpu

motion:
  improve_contrast: true
  contour_area: 15
  threshold: 18

go2rtc:
  streams:${GO2RTC_STREAMS}

cameras:${CAMERAS_SECTION}
ENDCONFIG

echo "generate-frigate-config: Written config with $(echo "$CAMERAS" | wc -w | tr -d ' ') camera(s) to ${CONFIG_FILE}"

# Execute the original entrypoint / command
exec "$@"
