#!/bin/sh
# generate-frigate-config.sh
# Auto-generates Frigate config.yml from CAMERA_*_RTSP_URL environment variables.
# Usage: This runs as the Frigate container entrypoint before Frigate starts.
#
# Convention: For each camera, set two env vars:
#   FRIGATE_CAMERA_<NAME>_RTSP_URL  — the RTSP stream URL
#   FRIGATE_CAMERA_<NAME>_ZONES     — optional, comma-separated zone definitions
#                                      format: zone_name:x1,y1,x2,y2,x3,y3,x4,y4
#
# Example:
#   FRIGATE_CAMERA_FRONT_RTSP_URL=rtsp://user:pass@192.168.1.50/stream1
#   FRIGATE_CAMERA_BACK_RTSP_URL=rtsp://user:pass@192.168.1.51/stream1
#   FRIGATE_CAMERA_PARKING_RTSP_URL=rtsp://user:pass@192.168.1.52/stream1
#   FRIGATE_CAMERA_FRONT_ZONES=front_door:0.05,0.95,0.38,0.95,0.38,0.40,0.05,0.40

set -e

CONFIG_DIR="${FRIGATE_CONFIG_DIR:-/config}"
CONFIG_FILE="${CONFIG_DIR}/config.yml"
DETECT_WIDTH="${FRIGATE_DETECT_WIDTH:-1280}"
DETECT_HEIGHT="${FRIGATE_DETECT_HEIGHT:-720}"
DETECT_FPS="${FRIGATE_DETECT_FPS:-5}"

# Discover cameras from environment variables matching FRIGATE_CAMERA_*_RTSP_URL
# Only include cameras whose URL is non-empty.
CAMERAS=""
for var in $(env | grep '^FRIGATE_CAMERA_.*_RTSP_URL=' | sed 's/=.*//' | sort); do
    eval url_val="\${$var}"
    if [ -z "$url_val" ]; then
        continue
    fi
    # Extract camera name: FRIGATE_CAMERA_FRONT_RTSP_URL -> front
    name=$(echo "$var" | sed 's/^FRIGATE_CAMERA_//;s/_RTSP_URL$//' | tr '[:upper:]' '[:lower:]')
    if [ -n "$name" ]; then
        CAMERAS="${CAMERAS} ${name}"
    fi
done

# Trim leading space
CAMERAS=$(echo "$CAMERAS" | sed 's/^ //')

if [ -z "$CAMERAS" ]; then
    echo "generate-frigate-config: WARNING — No cameras configured (all RTSP URLs empty)."
    echo "generate-frigate-config: Frigate will start with no cameras."
    # Write a minimal valid config so Frigate always starts.
    cat > "$CONFIG_FILE" <<ENDMINIMAL
# Auto-generated by generate-frigate-config.sh
# No cameras configured — add FRIGATE_CAMERA_*_RTSP_URL env vars and restart.

mqtt:
  enabled: false

tls:
  enabled: false

auth:
  enabled: false

birdseye:
  enabled: true

record:
  enabled: false

detectors:
  cpu1:
    type: cpu

cameras: {}
ENDMINIMAL
    echo "generate-frigate-config: Written minimal config (0 cameras) to ${CONFIG_FILE}"
    exec "$@"
fi

echo "generate-frigate-config: Discovered cameras: ${CAMERAS}"

# Build go2rtc streams section
GO2RTC_STREAMS=""
for cam in $CAMERAS; do
    upper=$(echo "$cam" | tr '[:lower:]' '[:upper:]')
    rtsp_var="FRIGATE_CAMERA_${upper}_RTSP_URL"
    eval rtsp_url="\${$rtsp_var}"
    GO2RTC_STREAMS="${GO2RTC_STREAMS}
    cam_${cam}:
      - \"${rtsp_url}\"
    cam_${cam}_live:
      - \"ffmpeg:cam_${cam}#video=h264\""
done

# Build cameras section
CAMERAS_SECTION=""
for cam in $CAMERAS; do
    upper=$(echo "$cam" | tr '[:lower:]' '[:upper:]')
    zones_var="FRIGATE_CAMERA_${upper}_ZONES"
    eval zones_val="\${$zones_var:-}"

    # Build zones YAML if defined
    ZONES_YAML=""
    if [ -n "$zones_val" ]; then
        ZONES_YAML="
    zones:"
        # Parse comma-separated zone definitions: name:coords;name2:coords2
        IFS=';'
        for zone_def in $zones_val; do
            zone_name=$(echo "$zone_def" | cut -d: -f1)
            zone_coords=$(echo "$zone_def" | cut -d: -f2-)
            ZONES_YAML="${ZONES_YAML}
      ${zone_name}:
        coordinates: ${zone_coords}
        inertia: 3
        loitering_time: 0"
        done
        unset IFS
    fi

    CAMERAS_SECTION="${CAMERAS_SECTION}
  cam_${cam}:
    enabled: true
    live:
      streams:
        main: cam_${cam}_live
    detect:
      enabled: true
      width: ${DETECT_WIDTH}
      height: ${DETECT_HEIGHT}
      fps: ${DETECT_FPS}
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam_${cam}
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      mask:
        - 0,0,1,0,1,0.06,0,0.06${ZONES_YAML}
    snapshots:
      enabled: true
"
done

# Write the config file
cat > "$CONFIG_FILE" <<ENDCONFIG
# Auto-generated by generate-frigate-config.sh
# Do not edit manually — changes will be overwritten on container restart.
# Configure cameras via FRIGATE_CAMERA_*_RTSP_URL environment variables.

mqtt:
  enabled: false

tls:
  enabled: false

auth:
  enabled: false

birdseye:
  enabled: true

record:
  enabled: false

snapshots:
  enabled: true
  retain:
    default: 7

objects:
  track:
    - person
    - car
    - motorcycle
    - bus
    - backpack
    - suitcase
    - handbag

detectors:
  cpu1:
    type: cpu

go2rtc:
  streams:${GO2RTC_STREAMS}

cameras:${CAMERAS_SECTION}
ENDCONFIG

echo "generate-frigate-config: Written config with $(echo "$CAMERAS" | wc -w | tr -d ' ') camera(s) to ${CONFIG_FILE}"

# Execute the original entrypoint / command
exec "$@"
