# generate-frigate-config.ps1
# Auto-generates Frigate config.yml from CAMERA_*_RTSP_URL environment variables.
# Windows equivalent of generate-frigate-config.sh for local testing/preview.
#
# Usage:
#   .\generate-frigate-config.ps1                         # uses env vars
#   .\generate-frigate-config.ps1 -EnvFile ..\.env        # loads from .env first
#   .\generate-frigate-config.ps1 -DryRun                 # print config to stdout
#
# Convention: For each camera, set env vars:
#   CAMERA_<NAME>_RTSP_URL          - the RTSP stream URL
#   CAMERA_<NAME>_SUBSTREAM_URL     - optional lower-res substream for detection
#   CAMERA_<NAME>_DETECT_WIDTH      - optional per-camera detect width
#   CAMERA_<NAME>_DETECT_HEIGHT     - optional per-camera detect height
#   CAMERA_<NAME>_ZONES             - optional, semicolon-separated zone definitions
#
# Example:
#   CAMERA_FRONT_RTSP_URL=rtsp://user:pass@192.168.1.50/stream1
#   CAMERA_FRONT_SUBSTREAM_URL=rtsp://user:pass@192.168.1.50/stream2
#   CAMERA_FRONT_ZONES=front_door:0.05,0.95,0.38,0.95,0.38,0.40,0.05,0.40

[CmdletBinding()]
param(
    [string]$ConfigDir,
    [string]$EnvFile,
    [switch]$DryRun
)

$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path -Parent $PSScriptRoot

# --- Defaults ----------------------------------------------------------------
if (-not $ConfigDir) {
    $ConfigDir = Join-Path $repoRoot 'config\frigate'
}
$ConfigFile = Join-Path $ConfigDir 'config.yml'
$DetectWidth  = if ($env:FRIGATE_DETECT_WIDTH)  { $env:FRIGATE_DETECT_WIDTH }  else { '1280' }
$DetectHeight = if ($env:FRIGATE_DETECT_HEIGHT) { $env:FRIGATE_DETECT_HEIGHT } else { '720' }
$DetectFps    = if ($env:FRIGATE_DETECT_FPS)    { $env:FRIGATE_DETECT_FPS }    else { '15' }

# --- Load .env file if specified ---------------------------------------------
if ($EnvFile) {
    if (-not (Test-Path $EnvFile)) {
        throw "Env file not found: $EnvFile"
    }
    Write-Host "generate-frigate-config: Loading env from $EnvFile" -ForegroundColor Cyan
    foreach ($line in Get-Content $EnvFile) {
        $line = $line.Trim()
        if ($line -eq '' -or $line.StartsWith('#')) { continue }
        if ($line -match '^([^=]+)=(.*)$') {
            $key = $Matches[1].Trim()
            $val = $Matches[2].Trim()
            # Strip optional surrounding quotes
            if ($val.Length -ge 2 -and (($val.StartsWith('"') -and $val.EndsWith('"')) -or ($val.StartsWith("'") -and $val.EndsWith("'")))) {
                $val = $val.Substring(1, $val.Length - 2)
            }
            [Environment]::SetEnvironmentVariable($key, $val, 'Process')
        }
    }
    # Re-read defaults after loading .env
    $DetectWidth  = if ($env:FRIGATE_DETECT_WIDTH)  { $env:FRIGATE_DETECT_WIDTH }  else { '1280' }
    $DetectHeight = if ($env:FRIGATE_DETECT_HEIGHT) { $env:FRIGATE_DETECT_HEIGHT } else { '720' }
    $DetectFps    = if ($env:FRIGATE_DETECT_FPS)    { $env:FRIGATE_DETECT_FPS }    else { '15' }
}

# --- Discover cameras --------------------------------------------------------
$cameraVars = Get-ChildItem env: |
    Where-Object { $_.Name -match '^CAMERA_(.+)_RTSP_URL$' -and $_.Name -notmatch '_SUBSTREAM_' -and $_.Value -ne '' } |
    Sort-Object Name

$cameras = @()
foreach ($var in $cameraVars) {
    if ($var.Name -match '^CAMERA_(.+)_RTSP_URL$') {
        $cameras += $Matches[1].ToLower()
    }
}

# --- Minimal config when no cameras found ------------------------------------
if ($cameras.Count -eq 0) {
    Write-Host 'generate-frigate-config: WARNING — No cameras configured (all RTSP URLs empty).' -ForegroundColor Yellow
    Write-Host 'generate-frigate-config: Frigate will start with no cameras.' -ForegroundColor Yellow

    $minimalConfig = @"
# Auto-generated by generate-frigate-config.ps1
# No cameras configured — add CAMERA_*_RTSP_URL env vars and restart.

mqtt:
  enabled: false

tls:
  enabled: false

auth:
  enabled: false

birdseye:
  enabled: true

record:
  enabled: false

detectors:
  cpu1:
    type: cpu

cameras: {}
"@

    if ($DryRun) {
        Write-Output $minimalConfig
    }
    else {
        New-Item -ItemType Directory -Force -Path $ConfigDir | Out-Null
        $minimalConfig | Set-Content -Path $ConfigFile -Encoding UTF8 -NoNewline
        Write-Host "generate-frigate-config: Written minimal config (0 cameras) to $ConfigFile" -ForegroundColor Green
    }
    return
}

Write-Host "generate-frigate-config: Discovered cameras: $($cameras -join ', ')" -ForegroundColor Cyan

# --- Build go2rtc streams ----------------------------------------------------
$go2rtcLines = @()
foreach ($cam in $cameras) {
    $upper = $cam.ToUpper()
    $rtspUrl = [Environment]::GetEnvironmentVariable("CAMERA_${upper}_RTSP_URL")
    $subUrl = [Environment]::GetEnvironmentVariable("CAMERA_${upper}_SUBSTREAM_URL")
    $go2rtcLines += "    cam_${cam}:"
    $go2rtcLines += "      - `"$rtspUrl`""
    $go2rtcLines += "    cam_${cam}_live:"
    $go2rtcLines += "      - `"ffmpeg:cam_${cam}#video=h264`""
    if ($subUrl) {
        $go2rtcLines += "    cam_${cam}_sub:"
        $go2rtcLines += "      - `"$subUrl`""
    }
}
$go2rtcStreams = $go2rtcLines -join "`n"

# --- Build tracked objects from TRACKED_ITEMS env var -------------------------
$trackedItems = if ($env:TRACKED_ITEMS) { $env:TRACKED_ITEMS } else { 'person,car,motorcycle,bus,backpack,suitcase,handbag' }
$trackList = ($trackedItems.Split(',') | ForEach-Object { "    - $($_.Trim())" }) -join "`n"

# --- Build cameras section ---------------------------------------------------
$cameraSections = @()
foreach ($cam in $cameras) {
    $upper = $cam.ToUpper()
    $zonesVal = [Environment]::GetEnvironmentVariable("CAMERA_${upper}_ZONES")
    $subUrl = [Environment]::GetEnvironmentVariable("CAMERA_${upper}_SUBSTREAM_URL")

    # Per-camera resolution overrides
    $camDw = [Environment]::GetEnvironmentVariable("CAMERA_${upper}_DETECT_WIDTH")
    $camDh = [Environment]::GetEnvironmentVariable("CAMERA_${upper}_DETECT_HEIGHT")
    $camFps = [Environment]::GetEnvironmentVariable("CAMERA_${upper}_DETECT_FPS")
    if (-not $camDw) { $camDw = $DetectWidth }
    if (-not $camDh) { $camDh = $DetectHeight }
    if (-not $camFps) { $camFps = $DetectFps }

    # Snapshot height based on detect resolution
    $snapHeight = 720
    if ([int]$camDh -ge 1080) { $snapHeight = 1080 }

    $zonesYaml = ''
    if ($zonesVal) {
        $zoneLines = @('    zones:')
        foreach ($zoneDef in $zonesVal.Split(';', [StringSplitOptions]::RemoveEmptyEntries)) {
            $parts = $zoneDef.Split(':', 2)
            $zoneName = $parts[0].Trim()
            $zoneCoords = $parts[1].Trim()
            $zoneLines += "      ${zoneName}:"
            $zoneLines += "        coordinates: $zoneCoords"
            $zoneLines += '        inertia: 3'
            $zoneLines += '        loitering_time: 0'
        }
        $zonesYaml = "`n" + ($zoneLines -join "`n")
    }

    # Build ffmpeg inputs (dual-stream or single-stream)
    if ($subUrl) {
        $ffmpegInputs = @"
      inputs:
        - path: rtsp://127.0.0.1:8554/cam_${cam}
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/cam_${cam}_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
"@
    } else {
        $ffmpegInputs = @"
      inputs:
        - path: rtsp://127.0.0.1:8554/cam_${cam}
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
"@
    }

    $cameraSections += @"
  cam_${cam}:
    enabled: true
    live:
      streams:
        main: cam_${cam}_live
    detect:
      enabled: true
      width: $camDw
      height: $camDh
      fps: $camFps
    ffmpeg:
$ffmpegInputs
    motion:
      mask:
        - 0,0,1,0,1,0.06,0,0.06${zonesYaml}
    snapshots:
      enabled: true
      quality: 95
      height: $snapHeight
"@
}
$camerasSection = $cameraSections -join "`n"

# --- Build full config -------------------------------------------------------
$fullConfig = @"
# Auto-generated by generate-frigate-config.ps1
# Do not edit manually — changes will be overwritten on container restart.
# Configure cameras via CAMERA_*_RTSP_URL environment variables in .env.

mqtt:
  enabled: false

tls:
  enabled: false

auth:
  enabled: false

birdseye:
  enabled: true

record:
  enabled: false

snapshots:
  enabled: true
  retain:
    default: 7

objects:
  track:
$trackList
  filters:
    person:
      min_score: 0.20
      threshold: 0.60
      min_area: 1000

detectors:
  cpu1:
    type: cpu

motion:
  improve_contrast: true
  contour_area: 15
  threshold: 18

go2rtc:
  streams:
$go2rtcStreams

cameras:
$camerasSection
"@

if ($DryRun) {
    Write-Output $fullConfig
}
else {
    New-Item -ItemType Directory -Force -Path $ConfigDir | Out-Null
    $fullConfig | Set-Content -Path $ConfigFile -Encoding UTF8 -NoNewline
    Write-Host "generate-frigate-config: Written config with $($cameras.Count) camera(s) to $ConfigFile" -ForegroundColor Green
}
