# generate-frigate-config.ps1
# Auto-generates Frigate config.yml from FRIGATE_CAMERA_*_RTSP_URL environment variables.
# Windows equivalent of generate-frigate-config.sh for local testing/preview.
#
# Usage:
#   .\generate-frigate-config.ps1                         # uses env vars
#   .\generate-frigate-config.ps1 -EnvFile ..\.env        # loads from .env first
#   .\generate-frigate-config.ps1 -DryRun                 # print config to stdout
#
# Convention: For each camera, set two env vars:
#   FRIGATE_CAMERA_<NAME>_RTSP_URL  - the RTSP stream URL
#   FRIGATE_CAMERA_<NAME>_ZONES     - optional, semicolon-separated zone definitions
#                                     format: zone_name:x1,y1,x2,y2,...;zone2:coords
#
# Example:
#   FRIGATE_CAMERA_FRONT_RTSP_URL=rtsp://user:pass@192.168.1.50/stream1
#   FRIGATE_CAMERA_FRONT_ZONES=front_door:0.05,0.95,0.38,0.95,0.38,0.40,0.05,0.40

[CmdletBinding()]
param(
    [string]$ConfigDir,
    [string]$EnvFile,
    [switch]$DryRun
)

$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path -Parent $PSScriptRoot

# --- Defaults ----------------------------------------------------------------
if (-not $ConfigDir) {
    $ConfigDir = Join-Path $repoRoot 'config\frigate'
}
$ConfigFile = Join-Path $ConfigDir 'config.yml'
$DetectWidth  = if ($env:FRIGATE_DETECT_WIDTH)  { $env:FRIGATE_DETECT_WIDTH }  else { '1280' }
$DetectHeight = if ($env:FRIGATE_DETECT_HEIGHT) { $env:FRIGATE_DETECT_HEIGHT } else { '720' }
$DetectFps    = if ($env:FRIGATE_DETECT_FPS)    { $env:FRIGATE_DETECT_FPS }    else { '5' }

# --- Load .env file if specified ---------------------------------------------
if ($EnvFile) {
    if (-not (Test-Path $EnvFile)) {
        throw "Env file not found: $EnvFile"
    }
    Write-Host "generate-frigate-config: Loading env from $EnvFile" -ForegroundColor Cyan
    foreach ($line in Get-Content $EnvFile) {
        $line = $line.Trim()
        if ($line -eq '' -or $line.StartsWith('#')) { continue }
        if ($line -match '^([^=]+)=(.*)$') {
            $key = $Matches[1].Trim()
            $val = $Matches[2].Trim()
            # Strip optional surrounding quotes
            if ($val.Length -ge 2 -and (($val.StartsWith('"') -and $val.EndsWith('"')) -or ($val.StartsWith("'") -and $val.EndsWith("'")))) {
                $val = $val.Substring(1, $val.Length - 2)
            }
            [Environment]::SetEnvironmentVariable($key, $val, 'Process')
        }
    }
    # Re-read defaults after loading .env
    $DetectWidth  = if ($env:FRIGATE_DETECT_WIDTH)  { $env:FRIGATE_DETECT_WIDTH }  else { '1280' }
    $DetectHeight = if ($env:FRIGATE_DETECT_HEIGHT) { $env:FRIGATE_DETECT_HEIGHT } else { '720' }
    $DetectFps    = if ($env:FRIGATE_DETECT_FPS)    { $env:FRIGATE_DETECT_FPS }    else { '5' }
}

# --- Discover cameras --------------------------------------------------------
$cameraVars = Get-ChildItem env: |
    Where-Object { $_.Name -match '^FRIGATE_CAMERA_(.+)_RTSP_URL$' -and $_.Value -ne '' } |
    Sort-Object Name

$cameras = @()
foreach ($var in $cameraVars) {
    if ($var.Name -match '^FRIGATE_CAMERA_(.+)_RTSP_URL$') {
        $cameras += $Matches[1].ToLower()
    }
}

# --- Minimal config when no cameras found ------------------------------------
if ($cameras.Count -eq 0) {
    Write-Host 'generate-frigate-config: WARNING — No cameras configured (all RTSP URLs empty).' -ForegroundColor Yellow
    Write-Host 'generate-frigate-config: Frigate will start with no cameras.' -ForegroundColor Yellow

    $minimalConfig = @"
# Auto-generated by generate-frigate-config.ps1
# No cameras configured — add FRIGATE_CAMERA_*_RTSP_URL env vars and restart.

mqtt:
  enabled: false

tls:
  enabled: false

auth:
  enabled: false

birdseye:
  enabled: true

record:
  enabled: false

detectors:
  cpu1:
    type: cpu

cameras: {}
"@

    if ($DryRun) {
        Write-Output $minimalConfig
    }
    else {
        New-Item -ItemType Directory -Force -Path $ConfigDir | Out-Null
        $minimalConfig | Set-Content -Path $ConfigFile -Encoding UTF8 -NoNewline
        Write-Host "generate-frigate-config: Written minimal config (0 cameras) to $ConfigFile" -ForegroundColor Green
    }
    return
}

Write-Host "generate-frigate-config: Discovered cameras: $($cameras -join ', ')" -ForegroundColor Cyan

# --- Build go2rtc streams ----------------------------------------------------
$go2rtcLines = @()
foreach ($cam in $cameras) {
    $upper = $cam.ToUpper()
    $rtspUrl = [Environment]::GetEnvironmentVariable("FRIGATE_CAMERA_${upper}_RTSP_URL")
    $go2rtcLines += "    cam_${cam}:"
    $go2rtcLines += "      - `"$rtspUrl`""
    $go2rtcLines += "    cam_${cam}_live:"
    $go2rtcLines += "      - `"ffmpeg:cam_${cam}#video=h264`""
}
$go2rtcStreams = $go2rtcLines -join "`n"

# --- Build cameras section ---------------------------------------------------
$cameraSections = @()
foreach ($cam in $cameras) {
    $upper = $cam.ToUpper()
    $zonesVal = [Environment]::GetEnvironmentVariable("FRIGATE_CAMERA_${upper}_ZONES")

    $zonesYaml = ''
    if ($zonesVal) {
        $zoneLines = @('    zones:')
        foreach ($zoneDef in $zonesVal.Split(';', [StringSplitOptions]::RemoveEmptyEntries)) {
            $parts = $zoneDef.Split(':', 2)
            $zoneName = $parts[0].Trim()
            $zoneCoords = $parts[1].Trim()
            $zoneLines += "      ${zoneName}:"
            $zoneLines += "        coordinates: $zoneCoords"
            $zoneLines += '        inertia: 3'
            $zoneLines += '        loitering_time: 0'
        }
        $zonesYaml = "`n" + ($zoneLines -join "`n")
    }

    $cameraSections += @"
  cam_${cam}:
    enabled: true
    live:
      streams:
        main: cam_${cam}_live
    detect:
      enabled: true
      width: $DetectWidth
      height: $DetectHeight
      fps: $DetectFps
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam_${cam}
          input_args: preset-rtsp-restream
          roles:
            - detect
            - snapshots
    motion:
      mask:
        - 0,0,1,0,1,0.06,0,0.06${zonesYaml}
    snapshots:
      enabled: true
      quality: 95
      height: 720
"@
}
$camerasSection = $cameraSections -join "`n"

# --- Build full config -------------------------------------------------------
$fullConfig = @"
# Auto-generated by generate-frigate-config.ps1
# Do not edit manually — changes will be overwritten on container restart.
# Configure cameras via FRIGATE_CAMERA_*_RTSP_URL environment variables.

mqtt:
  enabled: false

tls:
  enabled: false

auth:
  enabled: false

birdseye:
  enabled: true

record:
  enabled: false

snapshots:
  enabled: true
  retain:
    default: 7

objects:
  track:
    - person
    - car
    - motorcycle
    - bus
    - backpack
    - suitcase
    - handbag
  filters:
    person:
      min_score: 0.25
      threshold: 0.65
      min_area: 1500

detectors:
  cpu1:
    type: cpu

motion:
  improve_contrast: true
  contour_area: 20
  threshold: 20

go2rtc:
  streams:
$go2rtcStreams

cameras:
$camerasSection
"@

if ($DryRun) {
    Write-Output $fullConfig
}
else {
    New-Item -ItemType Directory -Force -Path $ConfigDir | Out-Null
    $fullConfig | Set-Content -Path $ConfigFile -Encoding UTF8 -NoNewline
    Write-Host "generate-frigate-config: Written config with $($cameras.Count) camera(s) to $ConfigFile" -ForegroundColor Green
}
